### ISSUE TITLE
Do not set default podSecurityContext in values.yaml

### ISSUE THREAD

**Issue by CrowdSalat** [cloudhut/charts#20]
Do not set default podSecurityContext in values.yaml, because security policies of a k8s cluster might force a specific range. Helm does not allow to unset a dictionary in values.yaml. It only allows to override given entries or add addional ones.

E.g. OpenShift allows only a specific user range which it will automatically pick if there is no (pod)securityContext set. If you cannot unset the podSecurityContext  you need to pick a valid value in the range, which is different for every cluster.

**Comment by weeco** [comment]
Hey @CrowdSalat ,
I'm unsure if that is also true for dictionaries, but my understanding was that you can override the values to the actual defaults by setting them to `null`. Did you try that? Is a dictionary a special case?

In case that's not possible: I absolutely understand your point, but I tend to remain opinionated about that. While this might be cumbersome/annoying defaults for some OpenShift users I think (given the effort to fix this) it is okay keep these defaults in favour of the enhanced security. Does that make sense?
