### ISSUE TITLE
Chart Versions

### ISSUE THREAD

**Issue by fanfoni** [cloudhut/charts#24]
Hey @weeco
It is possible to tag or use version branches in this repository?
This way it will be possible to pin the version in ArgoCD to avoid undesirable automatic rollouts.

Thanks =)

**Comment by weeco** [comment]
Hey @fanfoni ,
are you aware of the chart releases here? https://github.com/cloudhut/charts/tree/master/archives

Each new release is tagged with a semver compliant version or am I missing something?

**Comment by fanfoni** [comment]
Yes you are right, I was pointing directly to the git repository instead of using that directory as a helm repository.

Thank you =)
