### ISSUE TITLE
Reference brokers in different clusters

### ISSUE THREAD

**Issue by HighWatersDev** [cloudhut/charts#30]
Is there a way to reference brokers from different kafka clusters? I have 2 kafka clusters in 2 separate k8s clusters. Each cluster has its own set of ssl certificates for tls authentication.

I see in the chart, I can only reference brokers and tls once.

**Comment by weeco** [comment]
Hey, no multi-cluster support is not supported in Kowl. Therefore you are supposed to always setup one Kowl deployment per Kafka cluster.
