### ISSUE TITLE
secrets: not clear how to set TLS ones

### ISSUE THREAD

**Issue by dicolasi** [cloudhut/charts#9]
I got already a secret containing tls certificate. It is not clear to me how to point to it using this chart.

**Comment by dicolasi** [comment]
I can create a new secret as per Readme, however that would be a duplication.

**Comment by weeco** [comment]
Hey @dicolasi ,
I'm sorry for the late response. This usecase is described here:

https://github.com/cloudhut/charts/blob/master/kowl/values.yaml#L93-L108
and/or: https://github.com/cloudhut/charts#using-an-existing-secret

Does that help?

**Comment by dicolasi** [comment]
Yes thanks!
